library IEEE;
use IEEE.STD_LOGIC_1164.all;
use IEEE.STD_LOGIC_unsigned.all;

entity x7seg_top is
	port (
		CLK100MHZ : in STD_LOGIC;
	    SW : in STD_LOGIC_VECTOR(15 downto 0);
	    AN : out STD_LOGIC_VECTOR(7 downto 0);
		CT : out STD_LOGIC_VECTOR(6 downto 0);
		DP : out STD_LOGIC;
		LED : out  STD_LOGIC_VECTOR(3 downto 0)
	 );
end	 x7seg_top;

architecture x7seg_top of x7seg_top is

signal x: STD_LOGIC_VECTOR(31 downto 0);
signal s: STD_LOGIC_VECTOR(3 downto 0);
signal digit: STD_LOGIC_VECTOR(3 downto 0);
signal clkdiv: STD_LOGIC_VECTOR(18 downto 0);
signal clk : STD_LOGIC;

begin

    -- The main clock signal (renamed for ease of use)
    clk <= CLK100MHZ; 
    
    -- S is generated by a clock divider
    s <= clkdiv(18 downto 15);	
    	
	x(31 downto 16) <= X"0000";			-- 0 for top four segments
	x(15 downto 0) <= sw(15 downto 0);	-- value of number on switches
	
	dp <= '1';			   -- turn off dp
	LED <= digit;		   -- see the code
	
	-- Quad 8-to-1 MUX to select binary code to display
	process(s)
	begin
		case s is
		when "0000" => digit <= x(3 downto 0);
		when "0001" => digit <= x(7 downto 4);
		when "0010" => digit <= x(11 downto 8);
		when "0011" => digit <= x(15 downto 12);		
		when "0100" => digit <= x(19 downto 16);
		when "0101" => digit <= x(23 downto 20);	
		when "0110" => digit <= x(27 downto 24);	
		when others => digit <= x(31 downto 28);				
		end case;
	end process;
	
	-- Select a 7-seg display based on s
	process(s)
		variable aen : std_logic_vector(7 downto 0) := "11111111";
	begin
		aen := "11111111";
		aen(conv_integer(s)) := '0'; 
		an <= aen;
	end process;
	
    -- Clock divider
    process(clk)
    begin
        if clk'event and clk = '1' then
            clkdiv <= clkdiv +1;
        end if;
    end process;

	-- Decoder7-segment decoder: hex7seg
	process(digit)
	begin
	   case digit is
		   when X"0" => CT <=  "1000000";	 --0
		   when X"1" => CT <=  "1111001";	 --1
		   when X"2" => CT <=  "0100100";	 --2
		   when X"3" => CT <=  "0110000";	 --3
		   when X"4" => CT <=  "0011001";	 --4
		   when X"5" => CT <=  "0010010";	 --5
		   when X"6" => CT <=  "0000010";	 --6
		   when X"7" => CT <=  "1011000";	 --7
		   when X"8" => CT <=  "0000000";	 --8
		   when X"9" => CT <=  "0010000";	 --9
		   when X"A" => CT <=  "0001000";	 --A
		   when X"B" => CT <=  "0000011";	 --b
		   when X"C" => CT <=  "1000110";	 --C
		   when X"D" => CT <=  "0100001";	 --d
		   when X"E" => CT <=  "0000110";	 --E
		   when others => CT <=  "0001110";	 --F
	   end case;
	end process;
	
end x7seg_top;